services:
  # 1. O Serviço da API (FastAPI)
  - type: web
    name: ifinityads-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false # Você define o valor real no painel do Render
      - key: REDIS_URL
        fromService:
          type: redis
          name: ifinityads-cache
          property: connectionString
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false

  # 2. O Worker do Celery (Processamento de Vídeo)
  - type: worker
    name: ifinityads-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.core.tasks worker --loglevel=info
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: ifinityads-cache
          property: connectionString
      - key: REPLICATE_API_TOKEN
        sync: false

  # 3. Redis (Broker para o Celery)
  - type: redis
    name: ifinityads-cache
    ipAllowList: [] # Apenas serviços internos podem acessar